# Generated by Django 5.0.4 on 2025-08-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0003_requeststatus_servicecategory_worker_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='worker_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
