# Generated by Django 5.0.4 on 2025-08-16 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0004_worker_worker_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceapp.location'),
        ),
    ]
