# Generated by Django 5.0.4 on 2025-08-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0005_worker_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='worker_address',
        ),
        migrations.AddField(
            model_name='worker',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
