# Generated by Django 5.0.4 on 2025-08-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0006_remove_worker_worker_address_worker_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
