# Generated by Django 5.0.4 on 2025-08-17 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0009_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
