# Generated by Django 5.0.4 on 2025-08-17 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0010_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceapp.role'),
        ),
        migrations.AddField(
            model_name='worker',
            name='role_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceapp.role'),
        ),
    ]
