# Generated by Django 5.0.4 on 2025-08-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0011_user_role_id_worker_role_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='category',
        ),
        migrations.RemoveField(
            model_name='request',
            name='consumer',
        ),
        migrations.RemoveField(
            model_name='request',
            name='status',
        ),
        migrations.RemoveField(
            model_name='request',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='review',
            name='request',
        ),
        migrations.RemoveField(
            model_name='review',
            name='consumer',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='location',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='role_id',
        ),
        migrations.RemoveField(
            model_name='workerservice',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='workerservice',
            name='category',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
        migrations.DeleteModel(
            name='WorkerService',
        ),
    ]
