# Generated by Django 5.0.4 on 2025-08-18 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0012_remove_request_category_remove_request_consumer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
