# Generated by Django 5.0.4 on 2025-08-18 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0014_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='user',
        ),
        migrations.DeleteModel(
            name='RequestStatus',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
