# Generated by Django 5.0.4 on 2025-08-21 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0015_remove_request_user_delete_requeststatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceapp.servicecategory'),
        ),
    ]
