# Generated by Django 5.0.4 on 2025-08-22 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0016_user_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='category_id',
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('worker_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceapp.servicecategory')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceapp.location')),
            ],
        ),
    ]
